# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.api.uploads_api import UploadsApi


class TestUploadsApi(unittest.TestCase):
    """UploadsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UploadsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_upload(self) -> None:
        """Test case for cancel_upload

        Cancel an upload session
        """
        pass

    def test_complete_upload(self) -> None:
        """Test case for complete_upload

        Finalize a chunked upload
        """
        pass

    def test_create_upload(self) -> None:
        """Test case for create_upload

        Initialize a chunked upload session
        """
        pass

    def test_get_upload(self) -> None:
        """Test case for get_upload

        Get upload session status
        """
        pass

    def test_upload_part(self) -> None:
        """Test case for upload_part

        Upload a single chunk
        """
        pass


if __name__ == '__main__':
    unittest.main()
