# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.models.upload_status_response import UploadStatusResponse

class TestUploadStatusResponse(unittest.TestCase):
    """UploadStatusResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadStatusResponse:
        """Test UploadStatusResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadStatusResponse`
        """
        model = UploadStatusResponse()
        if include_optional:
            return UploadStatusResponse(
                id = '',
                status = 'uploading',
                file_name = '',
                total_chunks = 56,
                received_chunks = [
                    56
                    ],
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                source_width = 3840,
                source_height = 2160,
                source_duration_seconds = 600.0
            )
        else:
            return UploadStatusResponse(
                id = '',
                status = 'uploading',
                file_name = '',
                total_chunks = 56,
                received_chunks = [
                    56
                    ],
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testUploadStatusResponse(self):
        """Test UploadStatusResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
