# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.models.upload_job_source import UploadJobSource

class TestUploadJobSource(unittest.TestCase):
    """UploadJobSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UploadJobSource:
        """Test UploadJobSource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UploadJobSource`
        """
        model = UploadJobSource()
        if include_optional:
            return UploadJobSource(
                type = 'upload',
                upload_id = 'upl_01JQ8abc123'
            )
        else:
            return UploadJobSource(
                type = 'upload',
                upload_id = 'upl_01JQ8abc123',
        )
        """

    def testUploadJobSource(self):
        """Test UploadJobSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
