# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.api.downloads_api import DownloadsApi


class TestDownloadsApi(unittest.TestCase):
    """DownloadsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DownloadsApi()

    def tearDown(self) -> None:
        pass

    def test_download(self) -> None:
        """Test case for download

        Download an output file via signed token
        """
        pass


if __name__ == '__main__':
    unittest.main()
