# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.api.webhooks_api import WebhooksApi


class TestWebhooksApi(unittest.TestCase):
    """WebhooksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebhooksApi()

    def tearDown(self) -> None:
        pass

    def test_create_webhook(self) -> None:
        """Test case for create_webhook

        Register a webhook endpoint
        """
        pass

    def test_delete_webhook(self) -> None:
        """Test case for delete_webhook

        Soft-delete a webhook endpoint
        """
        pass

    def test_list_webhooks(self) -> None:
        """Test case for list_webhooks

        List active webhook endpoints
        """
        pass


if __name__ == '__main__':
    unittest.main()
