# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.models.job_output_info import JobOutputInfo

class TestJobOutputInfo(unittest.TestCase):
    """JobOutputInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobOutputInfo:
        """Test JobOutputInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobOutputInfo`
        """
        model = JobOutputInfo()
        if include_optional:
            return JobOutputInfo(
                state = 'pending',
                container = '',
                audio = True,
                target_height = 1080,
                width = 1920,
                height = 1080,
                bytes = 56,
                sha256 = '',
                retention_expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return JobOutputInfo(
                state = 'pending',
                container = '',
                audio = True,
        )
        """

    def testJobOutputInfo(self):
        """Test JobOutputInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
