# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.models.error_envelope import ErrorEnvelope

class TestErrorEnvelope(unittest.TestCase):
    """ErrorEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorEnvelope:
        """Test ErrorEnvelope
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorEnvelope`
        """
        model = ErrorEnvelope()
        if include_optional:
            return ErrorEnvelope(
                error = sophon_sdk.models.error_body.ErrorBody(
                    code = 'validation_error', 
                    message = '', 
                    retryable = True, 
                    request_id = '', )
            )
        else:
            return ErrorEnvelope(
                error = sophon_sdk.models.error_body.ErrorBody(
                    code = 'validation_error', 
                    message = '', 
                    retryable = True, 
                    request_id = '', ),
        )
        """

    def testErrorEnvelope(self):
        """Test ErrorEnvelope"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
