# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.models.job_source_info import JobSourceInfo

class TestJobSourceInfo(unittest.TestCase):
    """JobSourceInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobSourceInfo:
        """Test JobSourceInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobSourceInfo`
        """
        model = JobSourceInfo()
        if include_optional:
            return JobSourceInfo(
                name = '',
                bytes = 56,
                sha256 = '',
                duration_seconds = 1.337,
                resolution = '1920x1080',
                frame_rate = '23.976'
            )
        else:
            return JobSourceInfo(
                sha256 = '',
        )
        """

    def testJobSourceInfo(self):
        """Test JobSourceInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
