# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.models.job_progress import JobProgress

class TestJobProgress(unittest.TestCase):
    """JobProgress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JobProgress:
        """Test JobProgress
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JobProgress`
        """
        model = JobProgress()
        if include_optional:
            return JobProgress(
                stage = '',
                phase = 'queued',
                percent = 0,
                phase_percent = 0,
                fps = 1.337,
                eta_seconds = 56,
                frames_done = 56,
                frames_total = 56
            )
        else:
            return JobProgress(
                phase = 'queued',
                percent = 0,
        )
        """

    def testJobProgress(self):
        """Test JobProgress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
