# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.models.webhook_delivery_payload import WebhookDeliveryPayload

class TestWebhookDeliveryPayload(unittest.TestCase):
    """WebhookDeliveryPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WebhookDeliveryPayload:
        """Test WebhookDeliveryPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WebhookDeliveryPayload`
        """
        model = WebhookDeliveryPayload()
        if include_optional:
            return WebhookDeliveryPayload(
                event_id = 'evt_01JQabc123',
                type = 'job.completed',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                job_id = 'job_01JQ8C4K4W6YQ7M4M0A5K9T6RF',
                status = 'completed',
                metadata = { }
            )
        else:
            return WebhookDeliveryPayload(
                event_id = 'evt_01JQabc123',
                type = 'job.completed',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                job_id = 'job_01JQ8C4K4W6YQ7M4M0A5K9T6RF',
                status = 'completed',
                metadata = { },
        )
        """

    def testWebhookDeliveryPayload(self):
        """Test WebhookDeliveryPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
