# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.api.jobs_api import JobsApi


class TestJobsApi(unittest.TestCase):
    """JobsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = JobsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_job(self) -> None:
        """Test case for cancel_job

        Cancel a job
        """
        pass

    def test_create_job(self) -> None:
        """Test case for create_job

        Submit an encoding job
        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        Get a single job by ID
        """
        pass

    def test_get_job_output(self) -> None:
        """Test case for get_job_output

        Get the encoded output file
        """
        pass

    def test_list_jobs(self) -> None:
        """Test case for list_jobs

        List jobs with cursor pagination
        """
        pass


if __name__ == '__main__':
    unittest.main()
