# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sophon_sdk.models.create_job_request import CreateJobRequest

class TestCreateJobRequest(unittest.TestCase):
    """CreateJobRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateJobRequest:
        """Test CreateJobRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateJobRequest`
        """
        model = CreateJobRequest()
        if include_optional:
            return CreateJobRequest(
                source = sophon_sdk.models.upload_job_source.UploadJobSource(
                    type = 'upload', 
                    upload_id = 'upl_01JQ8abc123', ),
                profile = 'sophon-auto',
                output = sophon_sdk.models.create_job_output_options.CreateJobOutputOptions(
                    container = 'mp4', 
                    audio = True, 
                    target_height = 1080, ),
                webhook_ids = [
                    ''
                    ],
                metadata = { }
            )
        else:
            return CreateJobRequest(
                source = sophon_sdk.models.upload_job_source.UploadJobSource(
                    type = 'upload', 
                    upload_id = 'upl_01JQ8abc123', ),
                profile = 'sophon-auto',
        )
        """

    def testCreateJobRequest(self):
        """Test CreateJobRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
