"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from sophon_sdk.models.webhook_delivery_payload import WebhookDeliveryPayload

from sophon_sdk.api_client import ApiClient, RequestSerialized
from sophon_sdk.api_response import ApiResponse
from sophon_sdk.rest import RESTResponseType


class WebhookEventsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def receive_job_terminal_webhook(
        self,
        x_turbo_signature_256: ,
        x_turbo_event_id: ,
        x_turbo_timestamp: ,
        webhook_delivery_payload: ,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """Receive a terminal job webhook

        Outbound webhook delivery sent to registered webhook endpoints when a job reaches `completed`, `failed`, or `canceled`. Consumers should verify `X-Turbo-Signature-256` before processing. 

        :param x_turbo_signature_256: `sha256={hex}` — HMAC-SHA256 of `\"{X-Turbo-Timestamp}.{raw_body}\"` using the webhook's secret key.  (required)
        :type x_turbo_signature_256: str
        :param x_turbo_event_id: Unique event ID for consumer deduplication. (required)
        :type x_turbo_event_id: str
        :param x_turbo_timestamp: Timestamp used in signature computation. Check for replay. (required)
        :type x_turbo_timestamp: datetime
        :param webhook_delivery_payload: (required)
        :type webhook_delivery_payload: WebhookDeliveryPayload
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._receive_job_terminal_webhook_serialize(
            x_turbo_signature_256=x_turbo_signature_256,
            x_turbo_event_id=x_turbo_event_id,
            x_turbo_timestamp=x_turbo_timestamp,
            webhook_delivery_payload=webhook_delivery_payload,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def receive_job_terminal_webhook_with_http_info(
        self,
        x_turbo_signature_256: ,
        x_turbo_event_id: ,
        x_turbo_timestamp: ,
        webhook_delivery_payload: ,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """Receive a terminal job webhook

        Outbound webhook delivery sent to registered webhook endpoints when a job reaches `completed`, `failed`, or `canceled`. Consumers should verify `X-Turbo-Signature-256` before processing. 

        :param x_turbo_signature_256: `sha256={hex}` — HMAC-SHA256 of `\"{X-Turbo-Timestamp}.{raw_body}\"` using the webhook's secret key.  (required)
        :type x_turbo_signature_256: str
        :param x_turbo_event_id: Unique event ID for consumer deduplication. (required)
        :type x_turbo_event_id: str
        :param x_turbo_timestamp: Timestamp used in signature computation. Check for replay. (required)
        :type x_turbo_timestamp: datetime
        :param webhook_delivery_payload: (required)
        :type webhook_delivery_payload: WebhookDeliveryPayload
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._receive_job_terminal_webhook_serialize(
            x_turbo_signature_256=x_turbo_signature_256,
            x_turbo_event_id=x_turbo_event_id,
            x_turbo_timestamp=x_turbo_timestamp,
            webhook_delivery_payload=webhook_delivery_payload,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def receive_job_terminal_webhook_without_preload_content(
        self,
        x_turbo_signature_256: ,
        x_turbo_event_id: ,
        x_turbo_timestamp: ,
        webhook_delivery_payload: ,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Receive a terminal job webhook

        Outbound webhook delivery sent to registered webhook endpoints when a job reaches `completed`, `failed`, or `canceled`. Consumers should verify `X-Turbo-Signature-256` before processing. 

        :param x_turbo_signature_256: `sha256={hex}` — HMAC-SHA256 of `\"{X-Turbo-Timestamp}.{raw_body}\"` using the webhook's secret key.  (required)
        :type x_turbo_signature_256: str
        :param x_turbo_event_id: Unique event ID for consumer deduplication. (required)
        :type x_turbo_event_id: str
        :param x_turbo_timestamp: Timestamp used in signature computation. Check for replay. (required)
        :type x_turbo_timestamp: datetime
        :param webhook_delivery_payload: (required)
        :type webhook_delivery_payload: WebhookDeliveryPayload
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._receive_job_terminal_webhook_serialize(
            x_turbo_signature_256=x_turbo_signature_256,
            x_turbo_event_id=x_turbo_event_id,
            x_turbo_timestamp=x_turbo_timestamp,
            webhook_delivery_payload=webhook_delivery_payload,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _receive_job_terminal_webhook_serialize(
        self,
        x_turbo_signature_256,
        x_turbo_event_id,
        x_turbo_timestamp,
        webhook_delivery_payload,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_turbo_signature_256 is not None:
            _header_params['X-Turbo-Signature-256'] = x_turbo_signature_256
        if x_turbo_event_id is not None:
            _header_params['X-Turbo-Event-Id'] = x_turbo_event_id
        if x_turbo_timestamp is not None:
            _header_params['X-Turbo-Timestamp'] = x_turbo_timestamp
        # process the form parameters
        # process the body parameter
        if webhook_delivery_payload is not None:
            _body_params = webhook_delivery_payload



        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'sessionCookie', 
            'bearerApiKey'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/jobTerminalEvent',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


