# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from sophon_sdk.models.output_container import OutputContainer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateJobOutputOptions(BaseModel):
    """
    Optional output shaping knobs for a new job.
    """ # noqa: E501
    container: Optional[OutputContainer] = OutputContainer.MP4
    audio: Optional[StrictBool] = Field(default=False, description="When true, audio is included in the output. MKV preserves source audio streams unchanged. MP4 preserves broadly compatible source audio codecs when possible, and may normalize incompatible codecs to AAC for playback compatibility. When false, the output is video only. ")
    target_height: Optional[Annotated[int, Field(le=4320, strict=True, ge=144)]] = Field(default=None, description="Target output height in pixels. When set, output is scaled down (aspect ratio preserved, width derived from source, both dims rounded to even). If absent or larger than source height, output uses source dimensions. Billing tier is determined by the actual encoded output, not by this requested value. ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["container", "audio", "target_height"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateJobOutputOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateJobOutputOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "container": obj.get("container") if obj.get("container") is not None else OutputContainer.MP4,
            "audio": obj.get("audio") if obj.get("audio") is not None else False,
            "target_height": obj.get("target_height")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


