# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class JobProfile(str, Enum):
    """
    Encoding profile ID. Coffee-themed naming: prep time maps to encode speed, bare name is the 8-bit default (universal decoder compatibility), `-10bit` suffix opts into HEVC Main10 for higher-quality playback on newer decoders.  **8-bit (default):** - `sophon-espresso` — fastest, lowest compression - `sophon-cortado` — balanced speed and quality - `sophon-americano` — slowest, highest compression  **10-bit (HEVC Main10):** - `sophon-espresso-10bit` - `sophon-cortado-10bit` - `sophon-americano-10bit`  **Adaptive dispatcher:** - `sophon-auto` — public opt-in profile. The worker classifies   the source and records the concrete `effective_profile_id` on   the job once dispatch resolves. 
    """

    """
    allowed enum values
    """
    SOPHON_MINUS_ESPRESSO = 'sophon-espresso'
    SOPHON_MINUS_CORTADO = 'sophon-cortado'
    SOPHON_MINUS_AMERICANO = 'sophon-americano'
    SOPHON_MINUS_ESPRESSO_MINUS_10BIT = 'sophon-espresso-10bit'
    SOPHON_MINUS_CORTADO_MINUS_10BIT = 'sophon-cortado-10bit'
    SOPHON_MINUS_AMERICANO_MINUS_10BIT = 'sophon-americano-10bit'
    SOPHON_MINUS_AUTO = 'sophon-auto'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JobProfile from a JSON string"""
        return cls(json.loads(json_str))


