# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class JobSourceType(str, Enum):
    """
    Discriminator for `JobSource` variants.
    """

    """
    allowed enum values
    """
    UPLOAD = 'upload'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of JobSourceType from a JSON string"""
        return cls(json.loads(json_str))


