# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from sophon_sdk.models.job_output_info import JobOutputInfo
from sophon_sdk.models.job_profile import JobProfile
from sophon_sdk.models.job_progress import JobProgress
from sophon_sdk.models.job_source_info import JobSourceInfo
from sophon_sdk.models.job_status import JobStatus
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class JobResponse(BaseModel):
    """
    JobResponse
    """ # noqa: E501
    id: StrictStr
    status: JobStatus
    status_reason: Optional[StrictStr] = None
    attempt: StrictInt
    retryable: StrictBool = Field(description="Whether the job can still be retried (attempt < max_attempts and not terminal).")
    profile: JobProfile = Field(description="Public profile ID submitted by the customer. For adaptive jobs this stays `sophon-auto`; see `effective_profile_id` for the worker's resolved concrete profile. ")
    effective_profile_id: Optional[StrictStr] = Field(default=None, description="Concrete profile resolved by the worker. Omitted until dispatch resolves. On explicit-profile jobs this equals `profile`; on `sophon-auto` jobs it is an internal adaptive profile ID. ")
    source: JobSourceInfo
    progress: JobProgress
    output: JobOutputInfo
    metadata: Dict[str, Any] = Field(description="Arbitrary JSON object attached to a job. Keys and values are passed through unchanged to webhook deliveries and echoed on job reads. The serialized representation must not exceed 16 KiB. Free-form; SDKs surface this as a `Record<string, unknown>` / `dict[str, Any]` / `map[string]interface{}` depending on language. ")
    created_at: datetime
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    error: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "status", "status_reason", "attempt", "retryable", "profile", "effective_profile_id", "source", "progress", "output", "metadata", "created_at", "started_at", "completed_at", "error"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of JobResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of progress
        if self.progress:
            _dict['progress'] = self.progress.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output
        if self.output:
            _dict['output'] = self.output.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of JobResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "status_reason": obj.get("status_reason"),
            "attempt": obj.get("attempt"),
            "retryable": obj.get("retryable"),
            "profile": obj.get("profile"),
            "effective_profile_id": obj.get("effective_profile_id"),
            "source": JobSourceInfo.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "progress": JobProgress.from_dict(obj["progress"]) if obj.get("progress") is not None else None,
            "output": JobOutputInfo.from_dict(obj["output"]) if obj.get("output") is not None else None,
            "metadata": obj.get("metadata"),
            "created_at": obj.get("created_at"),
            "started_at": obj.get("started_at"),
            "completed_at": obj.get("completed_at"),
            "error": obj.get("error")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


