# coding: utf-8

"""
    SOPHON Encoding API

    REST API for submitting, monitoring, and retrieving SOPHON encoding jobs.  Authentication is via Bearer API key or session cookie. All POST endpoints require an Idempotency-Key header. List endpoints use opaque cursor-based pagination. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UploadStatusResponse(BaseModel):
    """
    UploadStatusResponse
    """ # noqa: E501
    id: StrictStr
    status: StrictStr
    file_name: StrictStr
    total_chunks: StrictInt
    received_chunks: List[StrictInt] = Field(description="Array of 0-indexed part numbers that have been received.")
    expires_at: datetime
    source_width: Optional[StrictInt] = Field(default=None, description="Source media width in pixels, populated from ffprobe after upload assembly. Null for uploads in `initiated`/`uploading` state or when probe failed. ")
    source_height: Optional[StrictInt] = Field(default=None, description="Source media height in pixels. See `source_width`.")
    source_duration_seconds: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Source media duration in seconds, from ffprobe after upload assembly. Used by the webapp free-tier budget check to compute realistic billable_seconds (5-second ceiling rounding). ")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "status", "file_name", "total_chunks", "received_chunks", "expires_at", "source_width", "source_height", "source_duration_seconds"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['uploading', 'assembling', 'completed', 'canceled']):
            raise ValueError("must be one of enum values ('uploading', 'assembling', 'completed', 'canceled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UploadStatusResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UploadStatusResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "file_name": obj.get("file_name"),
            "total_chunks": obj.get("total_chunks"),
            "received_chunks": obj.get("received_chunks"),
            "expires_at": obj.get("expires_at"),
            "source_width": obj.get("source_width"),
            "source_height": obj.get("source_height"),
            "source_duration_seconds": obj.get("source_duration_seconds")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


